language: python
python:
  - "3.6.5"
install:
  - pip install pip==19.1.1
  - pip -V
  - pip install --progress-bar  -r src/requirements_prod.txt
script:
  - export PYTHONPATH=./src
  - pytest --tb=short

